"use client";

import { Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import ProcurementTable from "@/components/ProcurementTable";
import RecommendationExplainability from "@/components/RecommendationExplainability";

type Result = { recommendations: Parameters<typeof ProcurementTable>[0]["recommendations"]; executive_summary: string; recommendedActions: string[]; keyRisks: string[]; assumptions: string[]; confidence: number; analysisStatus: "LIVE" | "STALE" | "UNAVAILABLE" };
function ProcurementPageContent() {
  const params = useSearchParams(); const suppliedGap = Number(params.get("gap")); const gap = Number.isFinite(suppliedGap) && suppliedGap >= 0 ? suppliedGap : 2.39;
  const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState("");
  useEffect(() => { let active = true; fetch("/api/procurement", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ supplyGapMbd: gap }) }).then(async (response) => { if (!response.ok) throw new Error("Procurement service unavailable"); return response.json() as Promise<Result>; }).then((data) => { if (active) setResult(data); }).catch((err) => { if (active) setError(err.message); }); return () => { active = false; }; }, [gap]);
  return <div className="space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-blue-700">Procurement orchestrator</p><h1 className="mt-1 text-3xl font-bold">Reroute the gap with a resilient basket.</h1><p className="mt-2 text-slate-600">Decision-support estimate for a <span className="font-semibold">{gap.toFixed(2)} mbd</span> scenario supply gap. Routing/capacity values are an <strong>indicative scenario</strong>, never cargo offers.</p></div>{error && <p className="rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}{!result ? <div className="rounded-xl border border-slate-200 bg-white p-8 text-center text-slate-500">Building ranked recommendations…</div> : <><section className="rounded-xl border border-blue-200 bg-blue-50 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold text-blue-950">Next six hours</h2><span className="rounded-full bg-white px-2.5 py-1 text-xs font-bold text-blue-900">Gemini analysis: {result.analysisStatus}</span></div><p className="mt-2 leading-7 text-blue-950">{result.executive_summary}</p>{result.analysisStatus !== "LIVE" && <p className="mt-3 text-sm font-semibold text-blue-900">Gemini unavailable — deterministic fallback used.</p>}{result.recommendedActions.length > 0 && <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-blue-950">{result.recommendedActions.map((action) => <li key={action}>{action}</li>)}</ul>}</section><ProcurementTable recommendations={result.recommendations} /><RecommendationExplainability recommendations={result.recommendations} confidence={result.confidence} /><p className="text-xs text-slate-500">Routing/capacity values are illustrative decision-support estimates, not cargo offers. Validate sanctions, grade compatibility, freight, insurance, port constraints, and cargo availability before execution.</p></>}</div>;
}
export default function ProcurementPage() { return <Suspense fallback={<div className="rounded-xl border border-slate-200 bg-white p-8 text-slate-500">Loading procurement orchestrator…</div>}><ProcurementPageContent /></Suspense>; }
