"use client";

type Item = { source_id: string; source_name: string; recommended_volume_mbd: number; extra_cost_estimate_pct: number; transit_days: number; rationale: string; risk_flag: "low" | "medium" | "high"; priority?: "high" | "medium" | "lower"; risk_signal?: string };
const flagClass = { low: "bg-emerald-100 text-emerald-800", medium: "bg-amber-100 text-amber-800", high: "bg-red-100 text-red-800" };
export default function ProcurementTable({ recommendations }: { recommendations: Item[] }) {
  return <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="p-4">Source</th><th className="p-4">Volume</th><th className="p-4">Cost premium</th><th className="p-4">Transit</th><th className="p-4">Risk / priority</th><th className="p-4">Rationale</th></tr></thead><tbody>
    {recommendations.map((item, index) => <tr key={item.source_id} className="border-t border-slate-100 align-top"><td className="p-4 font-semibold text-slate-900"><span className="mr-2 text-xs text-blue-700">Priority #{index + 1}</span>{item.source_name}</td><td className="p-4">{item.recommended_volume_mbd.toFixed(2)} mbd</td><td className="p-4">{item.extra_cost_estimate_pct > 0 ? "+" : ""}{item.extra_cost_estimate_pct}%</td><td className="p-4">{item.transit_days} days</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${flagClass[item.risk_flag]}`}>{item.risk_flag}</span>{item.priority && <p className="mt-1 text-xs text-slate-500">Priority: {item.priority}</p>}<p className="mt-1 max-w-40 text-xs text-slate-500">{item.risk_signal}</p></td><td className="p-4 text-slate-600">{item.rationale}</td></tr>)}
  </tbody></table></div>;
}
